import React, { useState, useEffect } from 'react';
import { base44 } from '@/api/base44Client';
import { Loader2, MapPin, Globe, Music } from 'lucide-react';

export default function PrintExport() {
  const [artist, setArtist] = useState(null);
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    loadArtist();
  }, []);

  const loadArtist = async () => {
    const params = new URLSearchParams(window.location.search);
    const artistId = params.get('artistId');
    
    if (!artistId) {
      setIsLoading(false);
      return;
    }

    try {
      const artists = await base44.entities.Artist.filter({ id: artistId });
      if (artists.length > 0) {
        setArtist(artists[0]);
      }
    } catch (error) {
      console.error('Error loading artist:', error);
    }
    setIsLoading(false);
  };

  if (isLoading) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-white">
        <Loader2 className="w-8 h-8 text-gray-400 animate-spin" />
      </div>
    );
  }

  if (!artist) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-white">
        <p className="text-gray-500">Artist not found</p>
      </div>
    );
  }

  return (
    <div className="bg-white min-h-screen text-black print:text-black">
      <style>{`
        @media print {
          body { -webkit-print-color-adjust: exact; print-color-adjust: exact; }
          .page-break { page-break-after: always; }
          .no-print { display: none !important; }
        }
      `}</style>

      {/* Print Instructions Banner */}
      <div className="no-print bg-emerald-600 text-white p-4 text-center sticky top-0 z-50">
        <p className="font-medium">
          Press <kbd className="px-2 py-1 bg-white/20 rounded mx-1">Ctrl/Cmd + P</kbd> to print or save as PDF
        </p>
      </div>

      {/* Cover Page */}
      <div className="min-h-screen flex flex-col items-center justify-center p-8 page-break">
        {artist.profilePhotoUrl && (
          <img 
            src={artist.profilePhotoUrl} 
            alt={artist.stageName}
            className="w-48 h-48 rounded-full object-cover mb-8 shadow-lg"
          />
        )}
        
        <h1 className="text-5xl font-bold text-center mb-4">
          {artist.stageName}
        </h1>
        
        {artist.tagline && (
          <p className="text-xl text-gray-600 text-center max-w-2xl mb-6">
            {artist.tagline}
          </p>
        )}

        {artist.primaryLocation && (
          <div className="flex items-center gap-2 text-gray-500 mb-8">
            <MapPin className="w-5 h-5" />
            <span>
              {artist.primaryLocation}
              {artist.secondaryLocation && ` / ${artist.secondaryLocation}`}
            </span>
          </div>
        )}

        {artist.genres?.length > 0 && (
          <div className="flex flex-wrap justify-center gap-2 mb-8">
            {artist.genres.map(genre => (
              <span 
                key={genre}
                className="px-4 py-2 bg-gray-100 rounded-full text-sm font-medium"
              >
                {genre}
              </span>
            ))}
          </div>
        )}

        <p className="text-sm text-gray-400 mt-auto">
          Electronic Press Kit • Generated by EPKForge
        </p>
      </div>

      {/* Bio Page */}
      <div className="min-h-screen p-8 page-break">
        <h2 className="text-3xl font-bold mb-8 pb-4 border-b-2 border-gray-200">
          Biography
        </h2>
        
        {artist.bioLong && (
          <div className="prose prose-lg max-w-none mb-12">
            <p className="whitespace-pre-line leading-relaxed">
              {artist.bioLong}
            </p>
          </div>
        )}

        {artist.bioShort && (
          <div className="bg-gray-50 p-6 rounded-lg">
            <h3 className="text-lg font-semibold mb-3">Quick Bio</h3>
            <p className="text-gray-700 italic">
              "{artist.bioShort}"
            </p>
          </div>
        )}
      </div>

      {/* Style & Highlights Page */}
      <div className="min-h-screen p-8 page-break">
        <h2 className="text-3xl font-bold mb-8 pb-4 border-b-2 border-gray-200">
          Musical Style & Highlights
        </h2>

        {/* Style */}
        <div className="mb-12">
          <h3 className="text-xl font-semibold mb-4">Musical Style</h3>
          
          <div className="grid grid-cols-2 gap-6">
            {artist.genres?.length > 0 && (
              <div>
                <h4 className="text-sm font-medium text-gray-500 mb-2">Genres</h4>
                <p className="font-medium">{artist.genres.join(', ')}</p>
              </div>
            )}
            
            {artist.vibes?.length > 0 && (
              <div>
                <h4 className="text-sm font-medium text-gray-500 mb-2">Vibes</h4>
                <p className="font-medium">{artist.vibes.join(', ')}</p>
              </div>
            )}

            {artist.styleThemes?.mood && (
              <div>
                <h4 className="text-sm font-medium text-gray-500 mb-2">Mood</h4>
                <p className="font-medium">{artist.styleThemes.mood}</p>
              </div>
            )}

            {artist.styleThemes?.style && (
              <div>
                <h4 className="text-sm font-medium text-gray-500 mb-2">Style</h4>
                <p className="font-medium">{artist.styleThemes.style}</p>
              </div>
            )}
          </div>
        </div>

        {/* Highlights */}
        {artist.highlights?.length > 0 && (
          <div>
            <h3 className="text-xl font-semibold mb-4">Career Highlights</h3>
            <ul className="space-y-3">
              {artist.highlights.map((highlight, index) => (
                <li key={index} className="flex items-start gap-3">
                  <div className="w-2 h-2 bg-emerald-500 rounded-full mt-2 flex-shrink-0" />
                  <span>{highlight}</span>
                </li>
              ))}
            </ul>
          </div>
        )}
      </div>

      {/* Links Page */}
      <div className="min-h-screen p-8">
        <h2 className="text-3xl font-bold mb-8 pb-4 border-b-2 border-gray-200">
          Links & Contact
        </h2>

        <div className="space-y-4 mb-12">
          {artist.verifiedLinks?.spotify && (
            <div className="flex items-center gap-4 p-4 bg-gray-50 rounded-lg">
              <div className="w-10 h-10 bg-green-500 rounded-lg flex items-center justify-center">
                <Music className="w-5 h-5 text-white" />
              </div>
              <div>
                <p className="font-medium">Spotify</p>
                <p className="text-sm text-gray-500">{artist.verifiedLinks.spotify}</p>
              </div>
            </div>
          )}

          {artist.verifiedLinks?.appleMusic && (
            <div className="flex items-center gap-4 p-4 bg-gray-50 rounded-lg">
              <div className="w-10 h-10 bg-pink-500 rounded-lg flex items-center justify-center">
                <Music className="w-5 h-5 text-white" />
              </div>
              <div>
                <p className="font-medium">Apple Music</p>
                <p className="text-sm text-gray-500">{artist.verifiedLinks.appleMusic}</p>
              </div>
            </div>
          )}

          {artist.verifiedLinks?.youtube && (
            <div className="flex items-center gap-4 p-4 bg-gray-50 rounded-lg">
              <div className="w-10 h-10 bg-red-500 rounded-lg flex items-center justify-center">
                <Globe className="w-5 h-5 text-white" />
              </div>
              <div>
                <p className="font-medium">YouTube</p>
                <p className="text-sm text-gray-500">{artist.verifiedLinks.youtube}</p>
              </div>
            </div>
          )}

          {artist.verifiedLinks?.instagram && (
            <div className="flex items-center gap-4 p-4 bg-gray-50 rounded-lg">
              <div className="w-10 h-10 bg-gradient-to-br from-purple-500 to-pink-500 rounded-lg flex items-center justify-center">
                <Globe className="w-5 h-5 text-white" />
              </div>
              <div>
                <p className="font-medium">Instagram</p>
                <p className="text-sm text-gray-500">{artist.verifiedLinks.instagram}</p>
              </div>
            </div>
          )}

          {artist.verifiedLinks?.tiktok && (
            <div className="flex items-center gap-4 p-4 bg-gray-50 rounded-lg">
              <div className="w-10 h-10 bg-black rounded-lg flex items-center justify-center">
                <Globe className="w-5 h-5 text-white" />
              </div>
              <div>
                <p className="font-medium">TikTok</p>
                <p className="text-sm text-gray-500">{artist.verifiedLinks.tiktok}</p>
              </div>
            </div>
          )}

          {artist.verifiedLinks?.website && (
            <div className="flex items-center gap-4 p-4 bg-gray-50 rounded-lg">
              <div className="w-10 h-10 bg-blue-500 rounded-lg flex items-center justify-center">
                <Globe className="w-5 h-5 text-white" />
              </div>
              <div>
                <p className="font-medium">Website</p>
                <p className="text-sm text-gray-500">{artist.verifiedLinks.website}</p>
              </div>
            </div>
          )}
        </div>

        {/* Press Links */}
        {artist.verifiedLinks?.press?.length > 0 && (
          <div className="mb-12">
            <h3 className="text-xl font-semibold mb-4">Press & Media</h3>
            <ul className="space-y-2">
              {artist.verifiedLinks.press.map((link, index) => (
                <li key={index} className="text-blue-600">
                  {link}
                </li>
              ))}
            </ul>
          </div>
        )}

        {/* Footer */}
        <div className="mt-auto pt-12 border-t border-gray-200 text-center text-sm text-gray-400">
          <p>Generated by EPKForge</p>
          <p>{new Date().toLocaleDateString()}</p>
        </div>
      </div>
    </div>
  );
}